export const properties = [
  {
    id: 1,
    name: 'Apartments at Palm Bay',
    location: 'Palm Bay FL',
    image: '1-Apartmets-at-Palm-Bay.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'apartments-at-palm-bay',
    description: 'TBA',
    size: 90,
    unit: 'units',
    details: [
      'TBA',
    ],
    gallery: [
      'Apartments-at-Palm-Bay-1.jpg',
      'Apartments-at-Palm-Bay-2.jpg',
      'Apartments-at-Palm-Bay-3.jpg',
      'Apartments-at-Palm-Bay-4.jpg',
      'Apartments-at-Palm-Bay-5.jpg',
      'Apartments-at-Palm-Bay-6.jpg',
    ],
    type: 'Multi-family',
  },
  {
    id: 2,
    name: 'Crela Spring Hill',
    location: 'Springhill FL',
    image: '2-Crela-Spring-Hill.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'crela-spring-hill',
    description: 'TBA',
    size: 162,
    unit: 'Townhomes',
    details: [
      'TBA',
    ],
    gallery: [
      'Crela-Spring-Hill-1.jpg',
      'Crela-Spring-Hill-2.jpg',
      'Crela-Spring-Hill-3.jpg',
      'Crela-Spring-Hill-4.jpg',
    ],
    type: 'Multi-family',
  },
  {
    id: 3,
    name: 'Cottages at Lake Hamilton',
    location: 'Winter Haven FL',
    image: '3-Cottages-at-Lake-Hamilton.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'cottages-at-lake-hamilton',
    description: 'TBA',
    size: 200,
    unit: 'units',
    details: [
      'TBA',
    ],
    gallery: [
      'Cottages-at-Lake-Hamilton-1.jpg',
      'Cottages-at-Lake-Hamilton-2.jpg',
      'Cottages-at-Lake-Hamilton-3.jpg',
    ],
    type: 'Multi-family',
  },
  {
    id: 4,
    name: 'Magnolia at Powell',
    location: 'Wildwood FL',
    image: '4-Magnolia-at-Powell.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'magnolia-at-powell',
    description: 'Coming soon to central Florida is Townhomes at Powell. Residential property adjacent to the villages.  A new residential townhome community with 132 units featuring luxury amenities including a resort style pool & Clubhouse area.',
    size: 132,
    unit: 'units',
    details: [
      'Apartments',
      'Townhomes',
    ],
    gallery: [
      'Magnolia-at-Powell-1.jpg',
      'Magnolia-at-Powell-2.jpg',
      'Magnolia-at-Powell-3.jpg',
    ],
    type: 'Multi-family',
  },
  {
    id: 5,
    name: 'Storage at Powell',
    location: 'Wildwood FL',
    image: '5-Storage-at-Powell.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'storage-at-powell',
    description: 'TBA',
    size: '100,000',
    unit: 'Sq Ft self-storage facility',
    details: [
      'TBA',
    ],
    gallery: [
      'Storage-at-Powell-1.jpg',
      'Storage-at-Powell-2.jpg',
      'Storage-at-Powell-3.jpg',
    ],
    type: 'Multi-family',
  },
  {
    id: 6,
    name: 'Solamar Wildwood',
    location: 'Wildwood FL',
    image: '6-Solamar-Wildwood.jpg',
    progress: 'Under Construction',
    status: 'in-process',
    slug: 'solamar-wildwood',
    description: 'Solamar Wildwood I, is a new residential rental community with a mixture of 248 Villas and Townhomes located in Wildwood, FL near the Villages! This project broke ground  Spring 2022. The property will feature both villas and townhomes with luxury amenities including a resort style pool & clubhouse area, Kids Play area, Dog Park & Dog Wash station as well as a BBQ Area and Gazebos for residents to enjoy the beautiful year-round Florida weather!',
    size: 243,
    unit: 'units',
    details: [
      'Villas',
      'Cottages',
      'Townhomes',
    ],
    gallery: [
      'Solamar-Wildwood-1.jpg',
      'Solamar-Wildwood-2.jpg',
      'Solamar-Wildwood-3.jpg',
      'Solamar-Wildwood-4.jpg',
    ],
    type: 'Multi-family',
  },
  {
    id: 7,
    name: 'Solamar Kissimmee (Old vineland Road)',
    location: 'Kissimmee FL',
    image: '7-Solamar-Kissimmee.jpg',
    progress: 'Completed',
    status: 'completed',
    slug: 'solamar-kissimmee',
    description: 'The Solamar project is a new 210 residential townhome rental community located in Kissimmee near Orlando, the heart of Florida! This project was completed in early Spring 2023 . The property will features private terraces with luxury amenities including a resort style pool & clubhouse area.',
    size: 212,
    unit: 'Townhomes',
    details: [
      'TBA',
    ],
    gallery: [
      'Solamar-Kissimmee-1.jpg',
      'Solamar-Kissimmee-2.jpg',
      'Solamar-Kissimmee-3.jpg',
    ],
    type: 'Multi-family',
  },
]